version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    environment:
      - POSTGRES_DB=zafira_db
      - POSTGRES_USER=zafira
      - POSTGRES_PASSWORD=zafira
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/zafira_db
      - SPRING_DATASOURCE_USERNAME=zafira
      - SPRING_DATASOURCE_PASSWORD=zafira
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  pgdata: